### ISSUE TITLE
后台-只要是内容介绍内容简介的那个框框都有这个问题

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#24]
不知道能不能描述清楚，问题是：我在甲文件夹中选了一个1.png的图片（叫它A）保存并上传，没有问题，但是如果我在同一个或者任意一个其他内容简介的地方，在乙文件夹中选了一个也叫1.png的图片（叫它B）并保存，则保存后，出现的图片，不是图片B，而是图片A。
![image](https://user-images.githubusercontent.com/23470504/29658717-7c9ce76c-88ee-11e7-950e-e180bfc01c23.png)
![image](https://user-images.githubusercontent.com/23470504/29658826-eaa42266-88ee-11e7-8309-5c99521d5b93.png)
![image](https://user-images.githubusercontent.com/23470504/29658852-0472e42a-88ef-11e7-8c8b-01133140d505.png)
![image](https://user-images.githubusercontent.com/23470504/29658894-2359db82-88ef-11e7-8647-11684e01e1c5.png)
个人文件夹情况仅作为参考，命名习惯如果比较一致的话，这个问题出现的概率还是蛮大的，还是要改的……
![image](https://user-images.githubusercontent.com/23470504/29659067-a283ed8a-88ef-11e7-99a3-1f8138639bfd.png)

**Comment by Alanbuddy** [comment]
需要查资料

**Comment by Alanbuddy** [comment]
先搁置
