### ISSUE TITLE
微信-课程-已购课程

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#38]
我理解邹总的意思是，只在购买后第一次跳转到课程详情页的时候，弹出窗口鼓励填写信息，以后打开该课程页，都不再弹出弹窗让填，直到用户下一次买了新课才又在弹出窗口。
现在是，我买了课程A，然后我不管是在课程列表页，还是我的课程或者我的收藏里进入页面，都要弹一次，而且不知道是不是不太稳定，这两种情况我都碰到过。
![image](https://user-images.githubusercontent.com/23470504/29702809-63c9c784-89a5-11e7-87c7-4bcc75d5772c.png)

**Comment by Alanbuddy** [comment]
已解决
