### ISSUE TITLE
微信-线上课程-课时详情

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#40]
这个逻辑应该是……当前可看的都是透明度100%，如图这种情况，如果123课时都上线了的话，那123都是亮的，4、5是有透明度的虚的。
![image](https://user-images.githubusercontent.com/23470504/29703562-a12b93c0-89a8-11e7-9353-a9db6fe67b72.png)

**Comment by Alanbuddy** [comment]
已解决
