### ISSUE TITLE
微信-音频课程-音频课时

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#41]
音频课时现在测试的相关情况如下：
1、jpg、png、gif格式都能传和播没问题。
2、正常观看的话，音频播放和图片切换都很顺畅，时间点也是准的。
3、如果有图片ABC，按照时间顺序设置配合音频，拖拽进度球，不同拖拽情况如下：
      a-在图片A显示时段，把进度拖到B的显示时段：之后一直显示图A，到图C的时间点了切换成图C
      b-在图片A显示时段，把进度拖到C的显示时段：之后一直显示图A
      c-在图片B显示时段，把进度拖到A的显示时段：之后一直显示图B，到图C的时间点了切换成图C
      d-在图片B显示时段，把进度拖到C的显示时段：之后一直显示图B
      e-在图片C显示时段，把进度拖到A的显示时段：之后一直显示图C
      f-在图片C显示时段，把进度拖到B的显示时段：之后一直显示图C
 不管咋样音频播放都很正常

**Comment by Alanbuddy** [comment]
暂时搁置

**Comment by Alanbuddy** [comment]
已解决
