### ISSUE TITLE
微信-线上课程-音频课时

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#42]
老问题，输入条又不见了……写评论的时候评论条不见了挺不好吧，况且咱这个评论条还比较矮
![image](https://user-images.githubusercontent.com/23470504/29705437-91669d24-89b0-11e7-99e7-5185cae64c70.png)

**Comment by Alanbuddy** [comment]
先搁置

**Comment by Alanbuddy** [comment]
安卓是正常的，iphone没有办法修复
