### ISSUE TITLE
微信-线上课程-课程评论

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#43]
首先是日期好像是没有获取？当时设定的应该是：32秒前，56分钟前，3小时前，3天前……超过7天的话就直接写日期，本来想的格式是2017/03/12这种格式，但是你们看吧，整个App里保持日期格式一致就好，要么都统一成2017年03月12日这样？
另，消息什么的里，日期也都是这样的
其次，右图一共有五条评论，但是出了三条之后，再怎么上拉都没反应了，上拉会抖动，很辣眼睛。
![image](https://user-images.githubusercontent.com/23470504/29706057-13dab70c-89b3-11e7-8bad-857fb9306e98.png)

**Comment by Alanbuddy** [comment]
先搁置

**Comment by Alanbuddy** [comment]
已解决
