### ISSUE TITLE
课程-线上课程-课时详情-评论

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#44]
在课时的每条评论下面，没有“课时来源”这个信息，因为来源都是当前课时
右图显示一个加载情况，实在很诡异，课时下面的这个评论，上拉加载的话，页面会跟得了帕金森一样边刷新边上下微微的抖，刷新的字样也有点一闪一闪，不知道什么情况
![image](https://user-images.githubusercontent.com/23470504/29706494-98f73cde-89b4-11e7-8de3-380fa1e41950.png)

**Comment by Alanbuddy** [comment]
已解决
