### ISSUE TITLE
微信-线下课程-课时情况

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#50]
每一课时的下面日期和时间，不是课程发布时日期和时间点，而是在后台设置时的
每个课时的日期和起止时间，在这里应该和手机上一一对应上。
![image](https://user-images.githubusercontent.com/23470504/29756773-16a88e5a-8bd9-11e7-8003-977bca4fde23.png)

**Comment by Alanbuddy** [comment]
需后台配合
