### ISSUE TITLE
后台-课程管理-线下课程

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#51]
在非编辑状态，点击也可删掉课时时间，这个问题不大，但不太好，状态如配图所示。
另，线下课程，不管是在新建的时候还是在编辑的时候，都没有像线上课程的一个“课程节数-设置时间数-标题数”的检验，怎么样都能提交，这个问题比较大。
![image](https://user-images.githubusercontent.com/23470504/29756789-39e47d5c-8bd9-11e7-9f00-33c752805743.png)

**Comment by Alanbuddy** [comment]
已解决
