### ISSUE TITLE
后台-讲师管理

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#52]
同名老师在选择时还是无法分辨识别
当时考虑的是利用备注来识别，在选择授课老师的列表中，有同名老师的话可以显示为——老师姓名（备注）的格式，如果没有备注的话，就显示为——老师姓名
而且，在线上课程这块儿还是，只能选前1,2个老师，被底下的课程介绍盖住了选不了
![image](https://user-images.githubusercontent.com/23470504/29756947-b7fb2fdc-8bda-11e7-87e5-41ba2e6811b8.png)

**Comment by Alanbuddy** [comment]
需后天配合

**Comment by Alanbuddy** [comment]
已修改
