### ISSUE TITLE
后台-课时管理

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#53]
视频和音频课时的内容介绍部分都有这个问题
传500K的图都传不上去，进度条有点闪烁，一会儿有一会儿没有，最后就报错
传30K的图有时能传上去，有时不能传上去，即使传上去了，也是进度条走到底，然后有5,6秒什么反应都没有，然后图片才闪现在框里。
![image](https://user-images.githubusercontent.com/23470504/29757110-0957c51a-8bdc-11e7-8bc3-5066076dd3bc.png)
![image](https://user-images.githubusercontent.com/23470504/29757125-1a6c7774-8bdc-11e7-96b3-54cfd4b8441e.png)

**Comment by Alanbuddy** [comment]
已解决
