### ISSUE TITLE
后台-新建视频课时

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#63]
如果课程介绍里都是图片没有文字，还是报没填写。按他们也有可能做一个长图不写字的，还是要改。
音频课时是好的，介绍里只有图片也可以提交
![image](https://user-images.githubusercontent.com/23470504/29910312-049b67f2-8e5c-11e7-8998-aa0a3315664d.png)

**Comment by Alanbuddy** [comment]
已解决
