### ISSUE TITLE
微信-首页

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#69]
切换排序方式，会有问题。
1、推荐课程我已经报名了评价了，就是一直没数据
2、最热里，线下课程，丢了啥时候开课
3、好评里，所有课程所学人数丢了

![image](https://user-images.githubusercontent.com/23470504/29954259-0fe797e0-8f09-11e7-81a5-b3310372a46d.png)

**Comment by Alanbuddy** [comment]
须后台配合
