### ISSUE TITLE
微信-线上课时-视频课时

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#75]
我就发了一个旅途兔兔，出现了两个，不知道什么原因，第一次点进来回看，还是只有一个，后来不知道为啥就是两个了。
![image](https://user-images.githubusercontent.com/23470504/29965040-b130b098-8f3e-11e7-9b81-8b5516b7a498.png)

**Comment by Alanbuddy** [comment]
已解决
