### ISSUE TITLE
微信-线上课程-课时详情-评论

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/WxMpVod#81]
给下面的最新点完赞，再给上面的点，可以点成负数
另，即使有赞数差距了，最赞也不是出现在上面三个，这个是什么规则呀现在？
![image](https://user-images.githubusercontent.com/23470504/30199963-991f7584-94a7-11e7-8f45-d1cafd797ae6.png)

**Comment by Alanbuddy** [comment]
已解决
